AWSTemplateFormatVersion: '2010-09-09'

Description: Create the Compute resources for the AEM Author

Parameters:

  ComputeStackPrefixParameter:
    Type: String
    Description: The AEM Stack Compute Resources Stack Prefix

  SSLCertificateARNParameter:
    Type: String
    Description: The ARN for SSL Certificate

  AuthorLoadBalancerHealthCheckTargetParameter:
    Type: String
    Description: AEM Author ELB Health Check Target

  AuthorSubnetAParameter:
    Type: AWS::EC2::Subnet::Id
    Description: The Author Subnet in Availability Zone A

  AuthorSubnetBParameter:
    Type: AWS::EC2::Subnet::Id
    Description: The Author Subnet in Availability Zone B

  AuthorInstanceProfileParameter:
    Type: String
    Description: The Author Instance Profile

  AuthorImageParameter:
    Type: AWS::EC2::Image::Id
    Description: The Author Image Id

  AuthorInstanceTypeParameter:
    Type: String
    Description: The Author Instance Type

  ComputeKeyPairNameParameter:
    Type: AWS::EC2::KeyPair::KeyName
    Description: The Compute Resources Key Pair Name

  AuthorRootVolSizeParameter:
    Type: Number
    Description: Author Instances Root EBS Volume Size

  AuthorDataVolSizeParameter:
    Type: Number
    Description: Author Instances Data EBS Volume Size

  UseAuthorDataVolSnapshotParameter:
    Type: String
    AllowedValues: [true, false]
    Description: Wheather to use the Author Snapshot Data Volume.

  AuthorDataVolSnapshotParamater:
    Type: String
    Description: The Author Data Volume Snapshot Id

  AuthorTagNameParameter:
    Type: String
    Description: The Author Name Tag

  AuthorLoadBalancerTagNameParameter:
    Type: String
    Description: The Author Load Balancer Name Tag

  RolesStackNameParameter:
    Type: String
    Description: The AEM Roles Stack Name

  SecurityGroupsStackNameParameter:
    Type: String
    Description: The AEM Security Groups Stack Name

  InboundFromBastionHostSecurityGroupParameter:
    Type: String
    Description: Inbound Bound from Bastion Host Security Group Id

  DataBucketNameParameter:
    Type: String
    Description: Bucket name that stores Stack data files

  AemAwsStackProvisionerVersionParameter:
    Type: String
    Description: AEM AWS Stack Provisioner version number

  MessagingStackNameParameter:
    Type: String
    Description: The Messaging Stack Name


Conditions:
  UseAuthorDataVolSnapshotCondition:
    Fn::Equals:
      - Ref: UseAuthorDataVolSnapshotParameter
      - true

Resources:

  AuthorSyncDelayAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      ActionsEnabled: true
      AlarmActions: 
        - Fn::ImportValue:
            Fn::Sub: ${MessagingStackNameParameter}-AlarmNotificationTopic
      AlarmDescription: Monitors the sync delay between the Author Standby and the Author Primary
      AlarmName: AEM Author Sync Delay Alarm
      ComparisonOperator: GreaterThanThreshold
      MetricName: seconds_since_last_sync
      Namespace: !Sub ${AWS::StackName}
      Period: 60
      EvaluationPeriods: 5
      Statistic: Maximum
      Threshold: 300
      Unit: Seconds

  AuthorPrimaryInstance:
    Type: AWS::EC2::Instance
    Properties:
      BlockDeviceMappings:
      - DeviceName: /dev/sda1
        Ebs:
          DeleteOnTermination: true
          VolumeSize:
            Ref: AuthorRootVolSizeParameter
          VolumeType: gp2
      - DeviceName: /dev/sdb
        Ebs:
          DeleteOnTermination: true
          VolumeSize:
            Ref: AuthorDataVolSizeParameter
          VolumeType: gp2
          SnapshotId:
            Fn::If:
              - UseAuthorDataVolSnapshotCondition
              - Ref: AuthorDataVolSnapshotParamater
              - Ref: AWS::NoValue
      IamInstanceProfile:
        Ref: AuthorInstanceProfileParameter
      ImageId:
        Ref: AuthorImageParameter
      InstanceType:
        Ref: AuthorInstanceTypeParameter
      KeyName:
        Ref: ComputeKeyPairNameParameter
      SecurityGroupIds:
      - Fn::ImportValue:
          Fn::Sub: ${SecurityGroupsStackNameParameter}-AuthorSecurityGroup
      - Ref: InboundFromBastionHostSecurityGroupParameter
      SubnetId:
        Ref: AuthorSubnetAParameter
      Tags:
      - Key: StackPrefix
        Value:
          Ref: ComputeStackPrefixParameter
      - Key: Name
        Value:
          Fn::Sub: ${AuthorTagNameParameter}-Primary
      - Key: Component
        Value: author-primary
      UserData:
        Fn::Base64:
          Fn::Sub: "#!/bin/bash -x\n\
            \ source /etc/profile\n\
            \ mkdir -p /opt/shinesolutions/aem-aws-stack-builder/\n\
            \ aws s3 cp s3://${DataBucketNameParameter}/${ComputeStackPrefixParameter}/stack-init.sh /opt/shinesolutions/aem-aws-stack-builder/stack-init.sh\n\
            \ chmod 755 /opt/shinesolutions/aem-aws-stack-builder/stack-init.sh\n\
            \ /opt/shinesolutions/aem-aws-stack-builder/stack-init.sh ${DataBucketNameParameter} ${ComputeStackPrefixParameter} author-primary ${AemAwsStackProvisionerVersionParameter}\n"

  AuthorStandbyInstance:
    Type: AWS::EC2::Instance
    Properties:
      BlockDeviceMappings:
      - DeviceName: /dev/sda1
        Ebs:
          DeleteOnTermination: true
          VolumeSize:
            Ref: AuthorRootVolSizeParameter
          VolumeType: gp2
      - DeviceName: /dev/sdb
        Ebs:
          DeleteOnTermination: true
          VolumeSize:
            Ref: AuthorDataVolSizeParameter
          VolumeType: gp2
          SnapshotId:
            Fn::If:
              - UseAuthorDataVolSnapshotCondition
              - Ref: AuthorDataVolSnapshotParamater
              - Ref: AWS::NoValue
      IamInstanceProfile:
        Ref: AuthorInstanceProfileParameter
      ImageId:
        Ref: AuthorImageParameter
      InstanceType:
        Ref: AuthorInstanceTypeParameter
      KeyName:
        Ref: ComputeKeyPairNameParameter
      SecurityGroupIds:
      - Fn::ImportValue:
          Fn::Sub: ${SecurityGroupsStackNameParameter}-AuthorSecurityGroup
      - Ref: InboundFromBastionHostSecurityGroupParameter
      SubnetId:
        Ref: AuthorSubnetBParameter
      Tags:
      - Key: StackPrefix
        Value:
          Ref: ComputeStackPrefixParameter
      - Key: Name
        Value:
          Fn::Sub: ${AuthorTagNameParameter}-Standby
      - Key: Component
        Value: author-standby
      - Key: AuthorPrimaryHost
        Value:
          Fn::GetAtt: [ AuthorPrimaryInstance, PrivateIp ]
      UserData:
        Fn::Base64:
          Fn::Sub: "#!/bin/bash -x\n\
            \ source /etc/profile\n\
            \ mkdir -p /opt/shinesolutions/aem-aws-stack-builder/\n\
            \ aws s3 cp s3://${DataBucketNameParameter}/${ComputeStackPrefixParameter}/stack-init.sh /opt/shinesolutions/aem-aws-stack-builder/stack-init.sh\n\
            \ chmod 755 /opt/shinesolutions/aem-aws-stack-builder/stack-init.sh\n\
            \ /opt/shinesolutions/aem-aws-stack-builder/stack-init.sh ${DataBucketNameParameter} ${ComputeStackPrefixParameter} author-standby ${AemAwsStackProvisionerVersionParameter}\n"

  AuthorLoadBalancer:
    Type: AWS::ElasticLoadBalancing::LoadBalancer
    Properties:
      ConnectionDrainingPolicy:
        Enabled: true
        Timeout: 300
      CrossZone: true
      HealthCheck:
        Target:
          Ref: AuthorLoadBalancerHealthCheckTargetParameter
        HealthyThreshold: '2'
        UnhealthyThreshold: '2'
        Interval: '30'
        Timeout: '5'
      Instances:
      - Ref: AuthorPrimaryInstance
      - Ref: AuthorStandbyInstance
      Listeners:
      - LoadBalancerPort: '80'
        InstancePort: '4502'
        Protocol: HTTP
      - LoadBalancerPort: '443'
        Protocol: HTTPS
        InstancePort: '5433'
        InstanceProtocol: HTTPS
        SSLCertificateId:
          Ref: SSLCertificateARNParameter
      Scheme: internal
      SecurityGroups:
      - Fn::ImportValue:
          Fn::Sub: ${SecurityGroupsStackNameParameter}-AuthorELBSecurityGroup
      - Ref: InboundFromBastionHostSecurityGroupParameter
      Subnets:
      - Ref: AuthorSubnetAParameter
      - Ref: AuthorSubnetBParameter
      Tags:
      - Key: Name
        Value:
          Fn::Sub: ${AuthorLoadBalancerTagNameParameter}
      - Key: StackPrefix
        Value:
          Ref: ComputeStackPrefixParameter

Outputs:

  AuthorPrimaryInstance:
    Value:
      Ref: AuthorPrimaryInstance
    Description: The Author Primary Instance

  AuthorStandbyInstance:
    Value:
      Ref: AuthorStandbyInstance
    Description: The Author Standby Instance

  AuthorLoadBalancer:
    Value:
      Ref: AuthorLoadBalancer
    Description: The Author Load Balancer

  AuthorLoadBalancerDNSName:
    Value:
      Fn::GetAtt: [AuthorLoadBalancer, DNSName]
    Export:
      Name:
        Fn::Sub: ${AWS::StackName}-LoadBalancerDNSName
    Description: The Author Load Balancer

  AuthorSyncDelayAlarm:
    Value:
      Ref: AuthorSyncDelayAlarm
    Description: The Author Sync Delay Alarm
