AWSTemplateFormatVersion: '2010-09-09'

Description: Create the Compute resources for the AEM Chaos Monkey

Parameters:

  ComputeStackPrefixParameter:
    Type: String
    Description: The AEM Stack Compute Resources Stack Prefix

  ChaosMonkeyInstanceProfileParameter:
    Type: String
    Description: The Chaos Monkey Instance Profile

  ChaosMonkeyImageParameter:
    Type: AWS::EC2::Image::Id
    Description: The Chaos Monkey Image Id

  ChaosMonkeyInstanceTypeParameter:
    Type: String
    Description: The Chaos Monkey Instance Type

  ComputeKeyPairNameParameter:
    Type: AWS::EC2::KeyPair::KeyName
    Description: The Compute Resources Key Pair Name

  ChaosMonkeyASGAvailabilityZoneListParameter:
    Type: List<AWS::EC2::AvailabilityZone::Name>
    Description: The Chaos Monkey Availability Zone List

  ChaosMonkeyASGSubnetListParameter:
    Type: List<AWS::EC2::Subnet::Id>
    Description: The Chaos Monkey Subnets

  ChaosMonkeyTagNameParameter:
    Type: String
    Description: The Chaos Monkey Name Tag

  ChaosMonkeyRootVolSizeParameter:
    Type: Number
    Description: Chaos Monkey Instances Root EBS Volum Size

  RolesStackNameParameter:
    Type: String
    Description: The AEM Roles Stack Name

  SecurityGroupsStackNameParameter:
    Type: String
    Description: The AEM Security Groups Stack Name

  OrchestratorStackNameParameter:
    Type: String
    Description: The AEM Orchestrator Role Stack Name

  PublishStackNameParameter:
    Type: String
    Description: The AEM Publish Role Stack Name

  PublishDispatcherStackNameParameter:
    Type: String
    Description: The AEM Publish Dispatcher Role Stack Name

  AuthorDispatcherStackNameParameter:
    Type: String
    Description: The AEM Author Dispatcher Role Stack Name

  InboundFromBastionHostSecurityGroupParameter:
    Type: String
    Description: Inbound Bound from Bastion Host Security Group Id

  DataBucketNameParameter:
    Type: String
    Description: Bucket name that stores Stack data files

  AemAwsStackProvisionerVersionParameter:
    Type: String
    Description: AEM AWS Stack Provisioner version number

Resources:


  ChaosMonkeyLaunchConfiguration:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      AssociatePublicIpAddress: false
      BlockDeviceMappings:
      - DeviceName: /dev/sda1
        Ebs:
          DeleteOnTermination: true
          VolumeSize:
            Ref: ChaosMonkeyRootVolSizeParameter
          VolumeType: gp2
      IamInstanceProfile:
        Ref: ChaosMonkeyInstanceProfileParameter
      ImageId:
        Ref: ChaosMonkeyImageParameter
      InstanceMonitoring: false
      InstanceType:
        Ref: ChaosMonkeyInstanceTypeParameter
      KeyName:
        Ref: ComputeKeyPairNameParameter
      SecurityGroups:
      - Fn::ImportValue:
          Fn::Sub: ${SecurityGroupsStackNameParameter}-ChaosMonkeySecurityGroup
      - Ref: InboundFromBastionHostSecurityGroupParameter
      UserData:
        Fn::Base64:
          Fn::Sub: "#!/bin/bash -x\n\
            \ source /etc/profile\n\
            \ mkdir -p /opt/shinesolutions/aem-aws-stack-builder/\n\
            \ aws s3 cp s3://${DataBucketNameParameter}/${ComputeStackPrefixParameter}/stack-init.sh /opt/shinesolutions/aem-aws-stack-builder/stack-init.sh\n\
            \ chmod 755 /opt/shinesolutions/aem-aws-stack-builder/stack-init.sh\n\
            \ /opt/shinesolutions/aem-aws-stack-builder/stack-init.sh ${DataBucketNameParameter} ${ComputeStackPrefixParameter} chaos-monkey ${AemAwsStackProvisionerVersionParameter}\n"
  ChaosMonkeyAutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      AvailabilityZones:
        Ref: ChaosMonkeyASGAvailabilityZoneListParameter
      HealthCheckGracePeriod: 300
      HealthCheckType: EC2
      LaunchConfigurationName:
        Ref: ChaosMonkeyLaunchConfiguration
      MaxSize: 1
      MinSize: 1
      Tags:
      - Key: Name
        Value:
          Fn::Sub: ${ChaosMonkeyTagNameParameter}
        PropagateAtLaunch: true
      - Key: StackPrefix
        Value:
          Ref: ComputeStackPrefixParameter
        PropagateAtLaunch: true
      - Key: Component
        Value: chaos-monkey
        PropagateAtLaunch: true
      - Key: OrchestratorASG
        Value:
          Fn::ImportValue:
            !Sub "${OrchestratorStackNameParameter}-OrchestratorAutoScalingGroup"
        PropagateAtLaunch: true
      - Key: PublisherASG
        Value:
          Fn::ImportValue:
            !Sub "${PublishStackNameParameter}-PublishAutoScalingGroup"
        PropagateAtLaunch: true
      - Key: PublisherDispatcherASG
        Value:
          Fn::ImportValue:
            !Sub "${PublishDispatcherStackNameParameter}-PublishDispatcherAutoScalingGroup"
        PropagateAtLaunch: true
      - Key: AuthorDispatcherASG
        Value:
          Fn::ImportValue:
            !Sub "${AuthorDispatcherStackNameParameter}-AuthorDispatcherAutoScalingGroup"
        PropagateAtLaunch: true
      VPCZoneIdentifier:
        Ref: ChaosMonkeyASGSubnetListParameter

Outputs:


  ChaosMonkeyLaunchConfiguration:
    Value:
      Ref: ChaosMonkeyLaunchConfiguration
    Description: The Chaos Monkey Launch Configuration

  ChaosMonkeyAutoScalingGroup:
    Value:
      Ref: ChaosMonkeyAutoScalingGroup
    Description: The Chaos Monkey Auto Scaling Group
