---
AWSTemplateFormatVersion: "2010-09-09"

Description:
  Create Messaging resources for the AEM Stack Auto Scaling Group Events

Parameters:

  AEMASGEventQueueNameParameter:
    Type: String
    Description: The AEM Stack Auto Scaling Group Event Quene Name

  AEMASGEventTopicDisplayNameParameter:
    Type: String
    Description: The AEM Stack Auto Scaling Group Event Topic Display Name

  AEMASGEventTopicNameParameter:
    Type: String
    Description: The AEM Stack Auto Scaling Group Event Topic Name

  AlarmNotificationTopicNameParameter:
    Type: String
    Description: AEM Sync Delay Alarm Topic Name

  AlarmNotificationContactEmailParameter:
    Type: String
    Description: AEM Sync Delay Alarm Contact Email (When alarm triggers)

Resources:

  AEMAutoScalingGroupEventQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName:
        Ref: AEMASGEventQueueNameParameter
      VisibilityTimeout: 60

  AEMASGEventTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName:
        Ref: AEMASGEventTopicDisplayNameParameter
      Subscription:
        - Endpoint:
            Fn::GetAtt: [ AEMAutoScalingGroupEventQueue, Arn ]
          Protocol: sqs
      TopicName:
        Ref: AEMASGEventTopicNameParameter

  AEMASGEventQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS: "*"
            Action:
              - sqs:SendMessage
            Resource:
              - Fn::GetAtt: [ AEMAutoScalingGroupEventQueue, Arn ]
            Condition:
              ArnEquals:
                aws:SourceArn:
                  Ref: AEMASGEventTopic
      Queues:
        - Ref: AEMAutoScalingGroupEventQueue

  AlarmNotificationTopic: 
    Type: AWS::SNS::Topic
    Properties: 
      Subscription: 
        - Endpoint: !Sub ${AlarmNotificationContactEmailParameter}
          Protocol: email
      TopicName: !Sub ${AlarmNotificationTopicNameParameter}

Outputs:

  AEMAutoScalingGroupEventQueue:
    Value:
      Ref: AEMAutoScalingGroupEventQueue
    Description: The AEM ASG Event Queue

  AEMASGEventTopic:
    Value:
      Ref: AEMASGEventTopic
    Description: The AEM ASG Event Topic
    Export:
      Name:
        Fn::Sub: ${AWS::StackName}-AEMASGEventTopic

  AlarmNotificationTopic:
    Value:
      Ref: AlarmNotificationTopic
    Description: The AEM Alarm Notification Topic
    Export:
      Name:
        Fn::Sub: ${AWS::StackName}-AlarmNotificationTopic
