AWSTemplateFormatVersion: '2010-09-09'

Description: Create the Compute resources for the AEM Orchestrator

Parameters:

  ComputeStackPrefixParameter:
    Type: String
    Description: The AEM Stack Compute Resources Stack Prefix

  OrchestratorInstanceProfileParameter:
    Type: String
    Description: The Orchestrator Instance Profile

  OrchestratorImageParameter:
    Type: AWS::EC2::Image::Id
    Description: The Orchestrator Image Id

  OrchestratorInstanceTypeParameter:
    Type: String
    Description: The Orchestrator Instance Type

  ComputeKeyPairNameParameter:
    Type: AWS::EC2::KeyPair::KeyName
    Description: The Compute Resources Key Pair Name

  OrchestratorASGAvailabilityZoneListParameter:
    Type: List<AWS::EC2::AvailabilityZone::Name>
    Description: The Orchestrator Availability Zone List

  OrchestratorASGSubnetListParameter:
    Type: List<AWS::EC2::Subnet::Id>
    Description: The Orchestrator Subnets

  OrchestratorRootVolSizeParameter:
    Type: Number
    Description: Orchestrator Instances Root EBS Volume Size

  OrchestratorDataVolSizeParameter:
    Type: Number
    Description: Orchestrator Instances Data EBS Volume Size

  OrchestratorTagNameParameter:
    Type: String
    Description: The Orchestrator Name Tag

  RolesStackNameParameter:
    Type: String
    Description: The AEM Roles Stack Name

  SecurityGroupsStackNameParameter:
    Type: String
    Description: The AEM Security Groups Stack Name

  InboundFromBastionHostSecurityGroupParameter:
    Type: String
    Description: Inbound Bound from Bastion Host Security Group Id

  DataBucketNameParameter:
    Type: String
    Description: Bucket name that stores Stack data files

  AemAwsStackProvisionerVersionParameter:
    Type: String
    Description: AEM AWS Stack Provisioner version number

Resources:


  OrchestratorLaunchConfiguration:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      AssociatePublicIpAddress: false
      BlockDeviceMappings:
      - DeviceName: /dev/sda1
        Ebs:
          DeleteOnTermination: true
          VolumeSize:
            Ref: OrchestratorRootVolSizeParameter
          VolumeType: gp2
      - DeviceName: /dev/sdb
        Ebs:
          DeleteOnTermination: true
          VolumeSize:
            Ref: OrchestratorDataVolSizeParameter
          VolumeType: gp2
      IamInstanceProfile:
        Ref: OrchestratorInstanceProfileParameter
      ImageId:
        Ref: OrchestratorImageParameter
      InstanceMonitoring: false
      InstanceType:
        Ref: OrchestratorInstanceTypeParameter
      KeyName:
        Ref: ComputeKeyPairNameParameter
      SecurityGroups:
      - Fn::ImportValue:
          Fn::Sub: ${SecurityGroupsStackNameParameter}-OrchestratorSecurityGroup
      - Ref: InboundFromBastionHostSecurityGroupParameter
      UserData:
        Fn::Base64:
          Fn::Sub: "#!/bin/bash -x\n\
            \ source /etc/profile\n\
            \ mkdir -p /opt/shinesolutions/aem-aws-stack-builder/\n\
            \ aws s3 cp s3://${DataBucketNameParameter}/${ComputeStackPrefixParameter}/stack-init.sh /opt/shinesolutions/aem-aws-stack-builder/stack-init.sh\n\
            \ chmod 755 /opt/shinesolutions/aem-aws-stack-builder/stack-init.sh\n\
            \ /opt/shinesolutions/aem-aws-stack-builder/stack-init.sh ${DataBucketNameParameter} ${ComputeStackPrefixParameter} orchestrator ${AemAwsStackProvisionerVersionParameter}\n"

  OrchestratorAutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      AvailabilityZones:
        Ref: OrchestratorASGAvailabilityZoneListParameter
      HealthCheckGracePeriod: 300
      HealthCheckType: EC2
      LaunchConfigurationName:
        Ref: OrchestratorLaunchConfiguration
      MaxSize: 1
      MinSize: 1
      Tags:
      - Key: Name
        Value:
          Fn::Sub: ${OrchestratorTagNameParameter}
        PropagateAtLaunch: true
      - Key: StackPrefix
        Value:
          Ref: ComputeStackPrefixParameter
        PropagateAtLaunch: true
      - Key: Component
        Value: orchestrator
        PropagateAtLaunch: true
      VPCZoneIdentifier:
        Ref: OrchestratorASGSubnetListParameter

Outputs:

  OrchestratorLaunchConfiguration:
    Value:
      Ref: OrchestratorLaunchConfiguration
    Description: The Orchestrator Launch Configuration

  OrchestratorAutoScalingGroup:
    Value:
      Ref: OrchestratorAutoScalingGroup
    Export:
      Name:
        Fn::Sub: ${AWS::StackName}-OrchestratorAutoScalingGroup
    Description: The Orchestrator Auto Scaling Group
